### ISSUE TITLE
Errors running demo

### ISSUE THREAD

**Issue by ecooper7** [CSTR-Edinburgh/Ossian#3]
Hello,

I am stepping through the demo example in the README and I get some errors which result in .cmp files not getting created.  I see that another user had this same issue and I tried reinstalling everything as they found to be the solution, but I still get the same errors.  The errors appear to start in the step 'acoustic_feature_extractor'.  What's strange is that the errors are e.g.

> Cannot open file /proj/tts/tools/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/cmp/adr_diph1_001.sp.double!

but that file does exist.  Also, when I separately run the command that appears to produce that error:

> /proj/tts/tools/Ossian//tools/bin//x2x +df /proj/tts/tools/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/cmp/adr_diph1_001.sp.double | /proj/tts/tools/Ossian//tools/bin//sopr -R -m 32768.0 | /proj/tts/tools/Ossian//tools/bin//mcep -a 0.77 -m 59 -l 2048.0 -j 0 -f 0.0 -q 3 > /proj/tts/tools/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn/cmp/adr_diph1_001.mgc

it runs without producing any error.  I am attaching the output from running the demo.  Any advice or suggestions are greatly appreciated.
[demo_out.txt](https://github.com/CSTR-Edinburgh/Ossian/files/1282562/demo_out.txt)

**Comment by oliverwatts** [comment]
Hi Erica,

I have just merged in a modification which might fix your problem. Please check out the latest version of scripts/processors/FeatureExtractor.py, clean up like:

`rm -r $OSSIAN/train/rm/speakers/rss_toy_demo/naive_01_nn/`

and try training again. Let me know if this fixes the problem.

**Comment by ecooper7** [comment]
Thanks Oliver -- it does now get through the step 5 acoustic_feature_extractor successfully, but fails now in step 7, pause_predictor.  Log output attached, it fails in SKLProccesors.py line 72:

> AttributeError: 'SKLDecisionTreePausePredictor' object has no attribute 'conf'

I tried taking out the reference to 'conf' in that line and re-ran, but it still fails the assertion that checks that the model has been trained.  
[demo2.txt](https://github.com/CSTR-Edinburgh/Ossian/files/1285286/demo2.txt)

**Comment by oliverwatts** [comment]
I have just made a commit (https://github.com/CSTR-Edinburgh/Ossian/commit/86b9837412a37ed2ea996e6b1cf127c10c35f47b) which might fix your problem. Please check out the latest scripts/processors/SKLProcessors.py, clean up as before:

`rm -r $OSSIAN/train/rm/speakers/rss_toy_demo/naive_01_nn/`

and try again. Please  me know if this fixes the problem.

**Comment by ecooper7** [comment]
all steps of the demo work now, thanks so much for all of your help!
